// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX4kIOw-GAF77gMNESB8IJ4_Ff6s-cDOY',
    appId: '1:444584461476:web:49f7c02425d254942c5231',
    messagingSenderId: '444584461476',
    projectId: 'sango-taxi-33a27',
    authDomain: 'sango-taxi-33a27.firebaseapp.com',
    storageBucket: 'sango-taxi-33a27.firebasestorage.app',
    measurementId: 'G-XTW4QYFE56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyw9PDT93V4eXQQ0_17BEU9mrdU6xlcB8',
    appId: '1:444584461476:android:4597f01ad2b6aa992c5231',
    messagingSenderId: '444584461476',
    projectId: 'sango-taxi-33a27',
    storageBucket: 'sango-taxi-33a27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcKFzY4eYxZ6rgTikhYfF2NJiCWBmfaYc',
    appId: '1:444584461476:ios:b2765ad58179d9c42c5231',
    messagingSenderId: '444584461476',
    projectId: 'sango-taxi-33a27',
    storageBucket: 'sango-taxi-33a27.firebasestorage.app',
    iosBundleId: 'com.example.itecmove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcKFzY4eYxZ6rgTikhYfF2NJiCWBmfaYc',
    appId: '1:444584461476:ios:b2765ad58179d9c42c5231',
    messagingSenderId: '444584461476',
    projectId: 'sango-taxi-33a27',
    storageBucket: 'sango-taxi-33a27.firebasestorage.app',
    iosBundleId: 'com.example.itecmove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX4kIOw-GAF77gMNESB8IJ4_Ff6s-cDOY',
    appId: '1:444584461476:web:393e9948030359502c5231',
    messagingSenderId: '444584461476',
    projectId: 'sango-taxi-33a27',
    authDomain: 'sango-taxi-33a27.firebaseapp.com',
    storageBucket: 'sango-taxi-33a27.firebasestorage.app',
    measurementId: 'G-X0017KSRC3',
  );

}